name: insurevis
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^5.0.0
  google_fonts: ^6.2.1
  stroke_text: ^1.0.0
  vector_graphics: ^1.1.18
  font_awesome_flutter: ^10.8.0
  flutter_screenutil: ^5.9.3
  auto_size_text: ^3.0.0
  camera: ^0.11.1
  http: ^1.3.0
  image_picker_web: ^4.0.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  http_parser: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
